######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 11 11:26:12 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
