# 

#bin/sum:obj/sum.o obj/main.o
#	gcc obj/sum.o obj/main.o -o bin/sum
#obj/sum.o:include/sum.h src/sum.c
#	gcc -Iinclude -c src/sum.c -o obj/sum.o
#obj/main.o:include/sum.h src/main.c
#	gcc -Iinclude -c src/main.c -o obj/main.o

#clean:
#	rm -rf obj/*.o bin/*






















bin/rc:include/rc.h src/rc.c
	gcc -Iinclude src/rc.c -o bin/rc
